export default {
  AD: 'Andorra',
  AE: 'Vereinigte Arabische Emirate',
  AF: 'Afghanistan',
  AG: 'Antigua und Barbuda',
  AI: 'Anguilla',
  AL: 'Albanien',
  AM: 'Armenien',
  AO: 'Angola',
  AQ: 'Antarktika',
  AR: 'Argentinien',
  AS: 'Amerikanischen Samoa-Inseln',
  AT: 'Österreich',
  AU: 'Australien',
  AW: 'Aruba',
  AX: 'Åland-Inseln',
  AZ: 'Aserbaidschan',
  BA: 'Bosnien und Herzegowina',
  BB: 'Barbados',
  BD: 'Bangladesch',
  BE: 'Belgien',
  BF: 'Burkina Faso',
  BG: 'Bulgarien',
  BH: 'Bahrein',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'saint Barthélemy',
  BM: 'Bermuda',
  BN: 'Brunei Darussalam',
  BO: 'Boliviens (Plurinationaler Staat)',
  BQ: 'Bonaire, Sint Eustatius und Saba',
  BR: 'Brasilien',
  BS: 'Bahamas',
  BT: 'Bhutan',
  BV: 'Bouvet-Insel',
  BW: 'Botswana',
  BY: 'Weißrussland',
  BZ: 'Belize',
  CA: 'Kanada',
  CC: 'Cocos (Keeling) Islands',
  CD: 'Kongo, Demokratische Republik der',
  CF: 'Zentralafrikanische Republik',
  CG: 'Kongo',
  CH: 'Schweiz',
  CI: "Côte d'Ivoire",
  CK: 'Cookinseln',
  CL: 'Chile',
  CM: 'Kamerun',
  CN: 'China',
  CO: 'Kolumbien',
  CR: 'Costa Rica',
  CU: 'Kuba',
  CV: 'Cabo Verde',
  CW: 'Curacao',
  CX: 'Weihnachtsinsel',
  CY: 'Zypern',
  CZ: 'Tschechien',
  DE: 'Deutschland',
  DJ: 'Dschibuti',
  DK: 'Dänemark',
  DM: 'Dominica',
  DO: 'Dominikanische Republik',
  DZ: 'Algerien',
  EC: 'Ecuador',
  EE: 'Estland',
  EG: 'Ägypten',
  EH: 'Westsahara',
  ER: 'Eritrea',
  ES: 'Spanien',
  ET: 'Äthiopien',
  FI: 'Finnland',
  FJ: 'Fidschi',
  FK: 'Falklandinseln (Malvinas)',
  FM: 'Mikronesien (Föderierte Staaten von)',
  FO: 'Färöer Inseln',
  FR: 'Frankreich',
  GA: 'Gabun',
  GB: 'Vereinigtes Königreich Großbritannien und Nordirland',
  GD: 'Grenada',
  GE: 'Georgia',
  GF: 'Französisch-Guayana',
  GG: 'Guernsey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Grönland',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadeloupe',
  GQ: 'Äquatorialguinea',
  GR: 'Griechenland',
  GS: 'Süd-Georgien und die südlichen Sandwich-Inseln',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HK: 'Hongkong',
  HM: 'Heard und McDonald-Inseln',
  HN: 'Honduras',
  HR: 'Kroatien',
  HT: 'Haiti',
  HU: 'Ungarn',
  ID: 'Indonesien',
  IE: 'Irland',
  IL: 'Israel',
  IM: 'Isle of Man',
  IN: 'Indien',
  IO: 'Britisches Territorium des Indischen Ozeans',
  IQ: 'Irak',
  IR: 'Iran (Islamic Republic of)',
  IS: 'Island',
  IT: 'Italien',
  JE: 'Jersey',
  JM: 'Jamaika',
  JO: 'Jordanien',
  JP: 'Japan',
  KE: 'Kenia',
  KG: 'Kirgisistan',
  KH: 'Kambodscha',
  KI: 'Kiribati',
  KM: 'Komoren',
  KN: 'St. Kitts und Nevis',
  KP: 'Korea, Demokratische Volksrepublik)',
  KR: 'Korea, Republik von',
  KW: 'Kuwait',
  KY: 'Cayman Inseln',
  KZ: 'Kasachstan',
  LA: 'Lao Demokratischen Volksrepublik',
  LB: 'Libanon',
  LC: 'St. Lucia',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesotho',
  LT: 'Litauen',
  LU: 'Luxemburg',
  LV: 'Lettland',
  LY: 'Libyen',
  MA: 'Marokko',
  MC: 'Monaco',
  MD: 'Moldawien',
  ME: 'Montenegro',
  MF: 'Saint Martin (Französisch Teil)',
  MG: 'Madagaskar',
  MH: 'Marshallinseln',
  MK: 'Nord Mazedonien',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolei',
  MO: 'Macao',
  MP: 'Nördliche Marianneninseln',
  MQ: 'Martinique',
  MR: 'Mauretanien',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Mauritius',
  MV: 'Malediven',
  MW: 'Malawi',
  MX: 'Mexiko',
  MY: 'Malaysia',
  MZ: 'Mosambik',
  NA: 'Namibia',
  NC: 'Neu-Kaledonien',
  NE: 'Niger',
  NF: 'Norfolkinsel',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Niederlande',
  NO: 'Norwegen',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'Neuseeland',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Peru',
  PF: 'Französisch Polynesien',
  PG: 'Papua Neu-Guinea',
  PH: 'Philippinen',
  PK: 'Pakistan',
  PL: 'Polen',
  PM: 'Saint-Pierre und Miquelon',
  PN: 'Pitcairn',
  PR: 'Puerto Rico',
  PS: 'Palästina, Bundesstaat',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Katar',
  RE: 'Wiedervereinigung',
  RO: 'Rumänien',
  RS: 'Serbien',
  RU: 'Russische Föderation',
  RW: 'Ruanda',
  SA: 'Saudi-Arabien',
  SB: 'Salomon-Inseln',
  SC: 'Seychellen',
  SD: 'Sudan',
  SE: 'Schweden',
  SG: 'Singapur',
  SH: 'St. Helena, Ascension und Tristan da Cunha',
  SI: 'Slowenien',
  SJ: 'Svalbard',
  SK: 'Slowakei',
  SL: 'Sierra Leone',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Suriname',
  SS: 'Südsudan',
  ST: 'Sao Tome und Principe',
  SV: 'El Salvador',
  SX: 'Sint Maarten (niederländischen Teil)',
  SY: 'Syrische Arabische Republik',
  SZ: 'Eswatini',
  TC: 'Turks- und Caicosinseln',
  TD: 'Tschad',
  TF: 'Südfranzösische Territorien',
  TG: 'Gehen',
  TH: 'Thailand',
  TJ: 'Tadschikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkmenistan',
  TN: 'Tunesien',
  TO: 'Tonga',
  TR: 'Truthahn',
  TT: 'Trinidad und Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan, Provinz Chinas',
  TZ: 'Tansania, Vereinigte Republik',
  UA: 'Ukraine',
  UG: 'Uganda',
  UM: 'United States Minor Outlying Islands',
  US: 'vereinigte Staaten von Amerika',
  UY: 'Uruguay',
  UZ: 'Usbekistan',
  VA: 'Heiliger Stuhl',
  VC: 'St. Vincent und die Grenadinen',
  VE: 'Venezuela (Bolivarische Republik)',
  VG: 'Virgin Inseln, Britisch)',
  VI: 'Virgin Islands (US)',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis und Futuna',
  WS: 'Samoa',
  YE: 'Jemen',
  YT: 'Mayotte',
  ZA: 'Südafrika',
  ZM: 'Sambia',
  ZW: 'Zimbabwe',
};
