export default {
  AE: 'UAE',
  BO: 'Bolivia',
  CD: 'Congo',
  CF: 'CAR',
  FK: 'Falkland Islands',
  FM: 'Micronesia',
  GB: 'United Kingdom',
  GS: 'SGSSI',
  IO: 'BIOT',
  IR: 'Iran',
  KP: 'North Korea',
  KR: 'South Korea',
  LA: 'Laos',
  MD: 'Moldova',
  MF: 'Saint Martin',
  PS: 'Palestine',
  RU: 'Russia',
  SX: 'Sint Maarten',
  TW: 'Taiwan',
  TZ: 'Tanzania',
  US: 'USA',
  VE: 'Venezuela',
  VG: 'Virgin Islands (British)',
  VI: 'Virgin Islands (US)',
};
