export default
{
  AD: 'Andorra',
  AE: 'Emiratos Árabes Unidos',
  AF: 'Afganistán',
  AG: 'Antigua y Barbuda',
  AI: 'Anguilla',
  AL: 'Albania',
  AM: 'Armenia',
  AO: 'Angola',
  AQ: 'Antártida',
  AR: 'Argentina',
  AS: 'Samoa Americana',
  AT: 'Austria',
  AU: 'Australia',
  AW: 'Aruba',
  AX: 'Islas Aland',
  AZ: 'Azerbaiyán',
  BA: 'Bosnia y Herzegovina',
  BB: 'Barbados',
  BD: 'Bangladesh',
  BE: 'Bélgica',
  BF: 'Burkina Faso',
  BG: 'Bulgaria',
  BH: 'Bahrein',
  BI: 'Burundi',
  BJ: 'Benin',
  BL: 'San Bartolomé',
  BM: 'islas Bermudas',
  BN: 'Brunei Darussalam',
  BO: 'Bolivia (Estado Plurinacional de)',
  BQ: 'Bonaire, San Eustaquio y Saba',
  BR: 'Brasil',
  BS: 'Bahamas',
  BT: 'Bután',
  BV: 'Isla Bouvet',
  BW: 'Botswana',
  BY: 'Bielorrusia',
  BZ: 'Belice',
  CA: 'Canadá',
  CC: 'Cocos (Keeling)',
  CD: 'Congo, República Democrática del',
  CF: 'República Centroafricana',
  CG: 'Congo',
  CH: 'Suiza',
  CI: 'Costa de Marfil',
  CK: 'Islas Cook',
  CL: 'Chile',
  CM: 'Camerún',
  CN: 'porcelana',
  CO: 'Colombia',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CW: 'Curaçao',
  CX: 'Isla de Navidad',
  CY: 'Chipre',
  CZ: 'Chequia',
  DE: 'Alemania',
  DJ: 'Djibouti',
  DK: 'Dinamarca',
  DM: 'dominica',
  DO: 'República Dominicana',
  DZ: 'Argelia',
  EC: 'Ecuador',
  EE: 'Estonia',
  EG: 'Egipto',
  EH: 'Sahara Occidental',
  ER: 'Eritrea',
  ES: 'España',
  ET: 'Etiopía',
  FI: 'Finlandia',
  FJ: 'Fiji',
  FK: 'Islas Malvinas (Falkland)',
  FM: 'Micronesia (Estados Federados de)',
  FO: 'Islas Faroe',
  FR: 'Francia',
  GA: 'Gabón',
  GB: 'Reino Unido de Gran Bretaña e Irlanda del Norte',
  GD: 'Granada',
  GE: 'Georgia',
  GF: 'Guayana francés',
  GG: 'Guernesey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Groenlandia',
  GM: 'Gambia',
  GN: 'Guinea',
  GP: 'Guadalupe',
  GQ: 'Guinea Ecuatorial',
  GR: 'Grecia',
  GS: 'Georgia del sur y las islas Sandwich del sur',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinea-Bissau',
  GY: 'Guayana',
  HK: 'Hong Kong',
  HM: 'Islas Heard y McDonald',
  HN: 'Honduras',
  HR: 'Croacia',
  HT: 'Haití',
  HU: 'Hungría',
  ID: 'Indonesia',
  IE: 'Irlanda',
  IL: 'Israel',
  IM: 'Isla del hombre',
  IN: 'India',
  IO: 'Territorio Británico del Océano Índico',
  IQ: 'Irak',
  IR: 'Irán (República Islámica de)',
  IS: 'Islandia',
  IT: 'Italia',
  JE: 'Jersey',
  JM: 'Jamaica',
  JO: 'Jordán',
  JP: 'Japón',
  KE: 'Kenia',
  KG: 'Kirguizistán',
  KH: 'Camboya',
  KI: 'Kiribati',
  KM: 'Comoras',
  KN: 'Saint Kitts y Nevis',
  KP: 'República de Corea, Popular Democrática de)',
  KR: 'Corea, república de',
  KW: 'Kuwait',
  KY: 'Islas Caimán',
  KZ: 'Kazajstán',
  LA: 'República Democrática Popular de Lao',
  LB: 'Líbano',
  LC: 'Santa Lucía',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Liberia',
  LS: 'Lesoto',
  LT: 'Lituania',
  LU: 'Luxemburgo',
  LV: 'Letonia',
  LY: 'Libia',
  MA: 'Marruecos',
  MC: 'Mónaco',
  MD: 'Moldavia, República de',
  ME: 'Montenegro',
  MF: 'San Martín (parte francesa)',
  MG: 'Madagascar',
  MH: 'Islas Marshall',
  MK: 'Norte Macedonia',
  ML: 'mali',
  MM: 'Myanmar',
  MN: 'Mongolia',
  MO: 'macao',
  MP: 'Islas Marianas del Norte',
  MQ: 'Martinica',
  MR: 'Mauritania',
  MS: 'Montserrat',
  MT: 'Malta',
  MU: 'Isla mauricio',
  MV: 'Maldivas',
  MW: 'Malawi',
  MX: 'México',
  MY: 'Malasia',
  MZ: 'Mozambique',
  NA: 'Namibia',
  NC: 'Nueva Caledonia',
  NE: 'Níger',
  NF: 'Isla Norfolk',
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Países Bajos',
  NO: 'Noruega',
  NP: 'Nepal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'Nueva Zelanda',
  OM: 'Omán',
  PA: 'Panamá',
  PE: 'Perú',
  PF: 'Polinesia francés',
  PG: 'Papúa Nueva Guinea',
  PH: 'Filipinas',
  PK: 'Pakistán',
  PL: 'Polonia',
  PM: 'San Pedro y Miquelón',
  PN: 'Pitcairn',
  PR: 'Puerto Rico',
  PS: 'Palestina, Estado de',
  PT: 'Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Katar',
  RE: 'Reunión',
  RO: 'Rumania',
  RS: 'Serbia',
  RU: 'Federación Rusa',
  RW: 'Ruanda',
  SA: 'Arabia Saudita',
  SB: 'Islas Salomón',
  SC: 'Seychelles',
  SD: 'Sudán',
  SE: 'Suecia',
  SG: 'Singapur',
  SH: 'Santa Helena, Ascensión y Tristán da Cunha',
  SI: 'Eslovenia',
  SJ: 'Svalbard y Jan Mayen',
  SK: 'Eslovaquia',
  SL: 'Sierra Leona',
  SM: 'San Marino',
  SN: 'Senegal',
  SO: 'Somalia',
  SR: 'Surinam',
  SS: 'Sudán del Sur',
  ST: 'Santo Tomé y Príncipe',
  SV: 'El Salvador',
  SX: 'Sint Maarten (parte neerlandesa)',
  SY: 'República Árabe Siria',
  SZ: 'Eswatini',
  TC: 'Islas Turcas y Caicos',
  TD: 'Chad',
  TF: 'Territorios Franceses del Sur',
  TG: 'Para llevar',
  TH: 'Tailandia',
  TJ: 'Tayikistán',
  TK: 'Tokelau',
  TL: 'Timor Oriental',
  TM: 'Turkmenistán',
  TN: 'Túnez',
  TO: 'Tonga',
  TR: 'pavo',
  TT: 'Trinidad y Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan, provincia de China',
  TZ: 'Tanzania, República Unida de',
  UA: 'Ucrania',
  UG: 'Uganda',
  UM: 'Islas periféricas menores de Estados Unidos',
  US: 'Estados Unidos de América',
  UY: 'Uruguay',
  UZ: 'Uzbekistán',
  VA: 'Santa Sede',
  VC: 'San Vicente y las Granadinas',
  VE: 'Venezuela (República Bolivariana de)',
  VG: 'Islas Vírgenes (británica)',
  VI: 'Islas Vírgenes (EE.UU.)',
  VN: 'Vietnam',
  VU: 'Vanuatu',
  WF: 'Wallis y Futuna',
  WS: 'Samoa',
  YE: 'Yemen',
  YT: 'Mayotte',
  ZA: 'Sudáfrica',
  ZM: 'Zambia',
  ZW: 'Zimbabue',
};
