export default {
  AD: 'Andorre',
  AE: 'Emirats Arabes Unis',
  AF: 'Afghanistan',
  AG: 'Antigua-et-Barbuda',
  AI: 'Anguilla',
  AL: 'Albanie',
  AM: 'Arménie',
  AO: 'Angola',
  AQ: 'Antarctique',
  AR: 'Argentine',
  AS: 'Samoa américaines',
  AT: "L'Autriche",
  AU: 'Australie',
  AW: 'Aruba',
  AX: 'Iles Aland',
  AZ: 'Azerbaïdjan',
  BA: 'Bosnie Herzégovine',
  BB: 'Barbade',
  BD: 'Bangladesh',
  BE: 'Belgique',
  BF: 'Burkina Faso',
  BG: 'Bulgarie',
  BH: 'Bahreïn',
  BI: 'Burundi',
  BJ: 'Bénin',
  BL: 'Saint Barthélemy',
  BM: 'Bermudes',
  BN: 'Brunei Darussalam',
  BO: 'Bolivie (État plurinational de)',
  BQ: 'Bonaire, Saint-Eustache et Saba',
  BR: 'Brésil',
  BS: 'Bahamas',
  BT: 'Bhoutan',
  BV: 'Île Bouvet',
  BW: 'Botswana',
  BY: 'Biélorussie',
  BZ: 'Belize',
  CA: 'Canada',
  CC: 'Îles Cocos (Keeling)',
  CD: 'Congo, République démocratique du',
  CF: 'République centrafricaine',
  CG: 'Congo',
  CH: 'la Suisse',
  CI: "Côte d'Ivoire",
  CK: 'les Îles Cook',
  CL: 'Chili',
  CM: 'Cameroun',
  CN: 'Chine',
  CO: 'Colombie',
  CR: 'Costa Rica',
  CU: 'Cuba',
  CV: 'Cabo Verde',
  CW: 'Curacao',
  CX: "L'île de noël",
  CY: 'Chypre',
  CZ: 'czechia',
  DE: 'Allemagne',
  DJ: 'Djibouti',
  DK: 'Danemark',
  DM: 'Dominique',
  DO: 'République Dominicaine',
  DZ: 'Algérie',
  EC: 'Equateur',
  EE: 'Estonie',
  EG: 'Egypte',
  EH: 'Sahara occidental',
  ER: 'Érythrée',
  ES: 'Espagne',
  ET: 'Ethiopie',
  FI: 'Finlande',
  FJ: 'Fidji',
  FK: 'Îles Falkland (Malvinas)',
  FM: 'Micronésie (États fédérés de)',
  FO: 'Îles Féroé',
  FR: 'France',
  GA: 'Gabon',
  GB: "Royaume-Uni de Grande-Bretagne et d'Irlande du Nord",
  GD: 'Grenade',
  GE: 'Géorgie',
  GF: 'Guyane Française',
  GG: 'Guernesey',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GL: 'Groenland',
  GM: 'Gambie',
  GN: 'Guinée',
  GP: 'Guadeloupe',
  GQ: 'Guinée Équatoriale',
  GR: 'Grèce',
  GS: 'Géorgie du Sud et les îles Sandwich du Sud',
  GT: 'Guatemala',
  GU: 'Guam',
  GW: 'Guinée-Bissau',
  GY: 'Guyane',
  HK: 'Hong Kong',
  HM: 'Les îles Heard et McDonald',
  HN: 'Honduras',
  HR: 'Croatie',
  HT: 'Haïti',
  HU: 'Hongrie',
  ID: 'Indonésie',
  IE: 'Irlande',
  IL: 'Israël',
  IM: 'île de Man',
  IN: 'Inde',
  IO: "Territoire britannique de l'océan Indien",
  IQ: 'Irak',
  IR: "Iran (République islamique d ')",
  IS: 'Islande',
  IT: 'Italie',
  JE: 'Jersey',
  JM: 'Jamaïque',
  JO: 'Jordan',
  JP: 'Japon',
  KE: 'Kenya',
  KG: 'Kirghizistan',
  KH: 'Cambodge',
  KI: 'Kiribati',
  KM: 'Comores',
  KN: 'Saint-Christophe-et-Niévès',
  KP: 'République populaire démocratique de Corée)',
  KR: 'Corée, République de',
  KW: 'Koweit',
  KY: 'Îles Caïmans',
  KZ: 'Kazakhstan',
  LA: 'République démocratique populaire lao',
  LB: 'Liban',
  LC: 'Sainte-Lucie',
  LI: 'Liechtenstein',
  LK: 'Sri Lanka',
  LR: 'Libéria',
  LS: 'Lesotho',
  LT: 'Lituanie',
  LU: 'Luxembourg',
  LV: 'Lettonie',
  LY: 'Libye',
  MA: 'Maroc',
  MC: 'Monaco',
  MD: 'Moldova, République de',
  ME: 'Monténégro',
  MF: 'Saint Martin (partie française)',
  MG: 'Madagascar',
  MH: 'Iles Marshall',
  MK: 'Macédoine du Nord',
  ML: 'Mali',
  MM: 'Myanmar',
  MN: 'Mongolie',
  MO: 'Macao',
  MP: 'Îles Mariannes du Nord',
  MQ: 'Martinique',
  MR: 'Mauritanie',
  MS: 'Montserrat',
  MT: 'Malte',
  MU: 'Ile Maurice',
  MV: 'Maldives',
  MW: 'Malawi',
  MX: 'Mexique',
  MY: 'Malaisie',
  MZ: 'Mozambique',
  NA: 'Namibie',
  NC: 'Nouvelle Calédonie',
  NE: 'Niger',
  NF: "l'ile de Norfolk",
  NG: 'Nigeria',
  NI: 'Nicaragua',
  NL: 'Pays-Bas',
  NO: 'Norvège',
  NP: 'Népal',
  NR: 'Nauru',
  NU: 'Niue',
  NZ: 'Nouvelle-Zélande',
  OM: 'Oman',
  PA: 'Panama',
  PE: 'Pérou',
  PF: 'Polynésie française',
  PG: 'Papouasie Nouvelle Guinée',
  PH: 'Philippines',
  PK: 'Pakistan',
  PL: 'Pologne',
  PM: 'Saint-Pierre-et-Miquelon',
  PN: 'Pitcairn',
  PR: 'Porto Rico',
  PS: 'Palestine, État de',
  PT: 'le Portugal',
  PW: 'Palau',
  PY: 'Paraguay',
  QA: 'Qatar',
  RE: 'Réunion',
  RO: 'Roumanie',
  RS: 'Serbie',
  RU: 'Fédération Russe',
  RW: 'Rwanda',
  SA: 'Arabie Saoudite',
  SB: 'Les îles Salomon',
  SC: 'les Seychelles',
  SD: 'Soudan',
  SE: 'Suède',
  SG: 'Singapour',
  SH: 'Sainte-Hélène, Ascension et Tristan da Cunha',
  SI: 'Slovénie',
  SJ: 'Spitzberg et Jan Mayen',
  SK: 'Slovaquie',
  SL: 'Sierra Leone',
  SM: 'Saint Marin',
  SN: 'Sénégal',
  SO: 'Somalie',
  SR: 'Suriname',
  SS: 'Soudan du sud',
  ST: 'Sao Tomé-et-Principe',
  SV: 'Le Salvador',
  SX: 'Sint Maarten (partie néerlandaise)',
  SY: 'République arabe syrienne',
  SZ: 'Eswatini',
  TC: 'îles Turques-et-Caïques',
  TD: 'Tchad',
  TF: 'Terres australes françaises',
  TG: 'Aller',
  TH: 'Thaïlande',
  TJ: 'Tadjikistan',
  TK: 'Tokelau',
  TL: 'Timor-Leste',
  TM: 'Turkménistan',
  TN: 'Tunisie',
  TO: 'Tonga',
  TR: 'dinde',
  TT: 'Trinité-et-Tobago',
  TV: 'Tuvalu',
  TW: 'Taiwan, Province de Chine',
  TZ: 'Tanzanie, République-Unie de',
  UA: 'Ukraine',
  UG: 'Ouganda',
  UM: 'Îles mineures éloignées des États-Unis',
  US: "les états-unis d'Amérique",
  UY: 'Uruguay',
  UZ: 'Ouzbékistan',
  VA: 'Saint-Siège',
  VC: 'Saint-Vincent-et-les-Grenadines',
  VE: 'Venezuela (République bolivarienne du)',
  VG: 'Îles Vierges (britanniques)',
  VI: 'Îles Vierges (États-Unis)',
  VN: 'Viet Nam',
  VU: 'Vanuatu',
  WF: 'Wallis et Futuna',
  WS: 'Samoa',
  YE: 'Yémen',
  YT: 'Mayotte',
  ZA: 'Afrique du Sud',
  ZM: 'Zambie',
  ZW: 'Zimbabwe',
};
